In [2]:
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import datasets
iris=datasets.load_iris()

x =  iris.data 
y = iris.target

# print ('sepal-length', 'sepal-width', 'petal-length', 'petal-width') 
# print(x)
# print('class: 0-Iris-Setosa, 1- Iris-Versicolour, 2- Iris-Virginica')
# print(y)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

#To Training the model and Nearest nighbors K=5	 
classifier = KNeighborsClassifier(n_neighbors=5) 
classifier.fit(x_train, y_train)

#to make predictions on our test data	 
y_pred=classifier.predict(x_test)

print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy Metrics') 
print(classification_report(y_test,y_pred))

Confusion Matrix
[[15  0  0]
 [ 0 13  0]
 [ 0  1 16]]
Accuracy Metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.93      1.00      0.96        13
           2       1.00      0.94      0.97        17

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a k-NN classifier
k = 3  # Number of neighbors to consider
knn = KNeighborsClassifier(n_neighbors=k)

# Train the classifier
knn.fit(X_train, y_train)

# Perform predictions on the test set
predictions = knn.predict(X_test)

# Print the correct and wrong predictions
correct = 0
wrong = 0
for i in range(len(predictions)):
    if predictions[i] == y_test[i]:
        print(f"Correct prediction: Predicted class '{iris.target_names[predictions[i]]}', Actual class '{iris.target_names[y_test[i]]}'")
        correct += 1
    else:
        print(f"Wrong prediction: Predicted class '{iris.target_names[predictions[i]]}', Actual class '{iris.target_names[y_test[i]]}'")
        wrong += 1

# Print the overall accuracy
accuracy = correct / (correct + wrong)
print(f"\nAccuracy: {accuracy:.2f}")


Correct prediction: Predicted class 'versicolor', Actual class 'versicolor'
Correct prediction: Predicted class 'setosa', Actual class 'setosa'
Correct prediction: Predicted class 'virginica', Actual class 'virginica'
Correct prediction: Predicted class 'versicolor', Actual class 'versicolor'
Correct prediction: Predicted class 'versicolor', Actual class 'versicolor'
Correct prediction: Predicted class 'setosa', Actual class 'setosa'
Correct prediction: Predicted class 'versicolor', Actual class 'versicolor'
Correct prediction: Predicted class 'virginica', Actual class 'virginica'
Correct prediction: Predicted class 'versicolor', Actual class 'versicolor'
Correct prediction: Predicted class 'versicolor', Actual class 'versicolor'
Correct prediction: Predicted class 'virginica', Actual class 'virginica'
Correct prediction: Predicted class 'setosa', Actual class 'setosa'
Correct prediction: Predicted class 'setosa', Actual class 'setosa'
Correct prediction: Predicted class 'setosa', Actu

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
